name: HelpingEva
main: io.github.woodog.helpingeva.HelpingEva
version: 0.3
commands:
  evapos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/evapos' to get current position, or '/pos x y z' to teleport to x,y,z"
    permission: helpingeva.evapos
    permission-message: You don't have <permission>
  evadebug:
    description: Toggles your debugging status for this plugin.
    usage: /evadebug