name: HelpingEva
main: io.github.woodog.helpingeva.HelpingEva
version: 0.1.6-topics_from_file-SNAPSHOT
commands:
  eva:
    description: Eva is a helping bot. Use /eva help for further infos.
    usage: "Usage: '/eva help' to get more help."
  eva.debug:
    description: Toggles your debugging status for this plugin.
    usage: "/eva.debug"
    permission: eva.debug
    permission-message: You don't have the permission <permission>
  eva.reload:
    description: Reloads Evas config file. 
    usage: "/eva.reload"
    permission: eva.reload
    permission-message: You don't have the permission <permission>
permissions:
  eva.*:
    description: Gives access to all helpingeva commands
    children:
      eva.basic: true
      eva.debug: op
      eva.reload: op
  eva.basic:
    description: Allows you to use eva basic commands
    default: true
  eva.debug:
    description: Print debugging information to console
    default: op
  eva.reload:
    description: Reload Evas config file
    default: op
      